### ISSUE TITLE
'server' is already declared in the upper scope.

### ISSUE THREAD

**Issue by derberg** [asyncapi/glee#114]
Details: https://sonarcloud.io/project/issues?id=asyncapi_glee&issues=AXqhLDqqAeRbydshud2H&open=AXqhLDqqAeRbydshud2H

Code: `src/lib/adapter.js`

Explanation: Variables should not be shadowed. Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they’re using one variable but are really using another.

**Comment by NuclearCactus** [comment]
Please assign me this issue, I'll get to fixing immediately
