### ISSUE TITLE
'./lib/runtimes/index.js' import is duplicated.

### ISSUE THREAD

**Issue by derberg** [asyncapi/glee#116]
details: https://sonarcloud.io/project/issues?id=asyncapi_glee&issues=AXqaiNN0P8p3iozZcvlZ&open=AXqaiNN0P8p3iozZcvlZ

code: `src/index.js`

**Comment by kanumalivad** [comment]
Kindly assign to me

**Comment by joeljose350** [comment]
I have opened a pull request that fixes this issue.

**Comment by magicmatatjahu** [comment]
Resolved by #117
