### ISSUE TITLE
Make linter stricter on formatting of js files

### ISSUE THREAD

**Issue by panwauu** [asyncapi/glee#148]
#### Describe the bug
I noticed some inconsitencies in the formatting of the js files. While this is not critical at all, it is annoying for me as I cant configure my environment to use formatting on save as this always produces changes. I am no expert with the .eslintrc files. Is there another asnycapi project with an up-to-date version that can be reused here? 
I think the linter should enforce behavior close to many standart formatters such that anyone can use their default.

1. Empty lines sometimes contain spaces and sometimes they dont (Should always be empty)
2. Between function names and the signature in braces there is sometimes a space and sometimes there is none (Should never be one)
3. Sometimes there are two instead of one space or spaces at the end of lines (Should not allow unneeded spaces)

All can be found in lib/adapter.js
1. https://github.com/asyncapi/glee/blob/ae20715b70b3ecb45273ef0d05f0126606e5d27a/src/lib/adapter.js#L20
2. https://github.com/asyncapi/glee/blob/ae20715b70b3ecb45273ef0d05f0126606e5d27a/src/lib/adapter.js#L14
3. https://github.com/asyncapi/glee/blob/ae20715b70b3ecb45273ef0d05f0126606e5d27a/src/lib/adapter.js#L33

**Comment by sudoshreyansh** [comment]
Can I work on this issue ?

**Comment by Ankitchaudharyy** [comment]
I can work on this issue.
