### ISSUE TITLE
feat: Glee's message sending API should be as DRY as possible

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/glee#192]
Glee supports message handlers (which are invoked upon receiving a message) as well as the sending of messages (typically from within message handlers).

- When sending a message, a Glee app makes use of `OutboundMessage`s, which can be used to `send`, `reply`, and/or `broadcast` a message (https://github.com/asyncapi/glee/blob/master/docs/functions.md).
- Also, `OutboundMessage` contains the `channel` property, which specifies the channel the message is sent to.
- Lastly, the message interactions performed by the Glee app are specified by an AsyncAPI document.

All the above options (`send`, `reply`, `broadcast` and `channel`) specify various aspects of sending a message, which must however always be in accordance with the AsyncAPI document of the Glee application. There is significant overlap between the information contained in these options. In other words, the current API o send messages is not DRY.

Ideally, given an AsyncAPI document, a Glee app should just need one operation to send a message to a channel. Specifically:

- The differences between `send` and `broadcast` should not matter to the Glee app.
- A `reply` is just a send to a reply channel specified by the sender of the incoming message, optionally with the message ID of the incoming message included in the reply message. All of that information should already be in the AsyncAPI document.

In general, every aspect of the messages sent by the Glee app should be specified in the AsyncAPI document - if at all possible - and not be repeated in Glee's message sending API. Only information that cannot be expressed in AsyncAPI should be part of Glee's message sending API (or be included in future versions of the AsyncAPI spec ;) ).

See https://asyncapi.slack.com/archives/CQVJXFNQL/p1637667052282600 for the origins of this request.

**Comment by fmvilas** [comment]
Just to add to what you said:

* A Glee app can be a server (eg., WebSocket or HTTP server), a client (eg., MQTT), or both (eg., a WS server and an MQTT client).
* Only servers should have the "broadcast" functionality. That isn't to say there should be a `broadcast` keyword. In the case of servers, `send` should behave as "broadcasting to all clients" and `reply` should behave as "sending to a specific client".
* In the case of clients, `send` should send a message to a broker or server and `reply` should send a message to a broker or server as a response or side-effect of receiving a message.

**Comment by sudoshreyansh** [comment]
Can I work on this issue ?

**Comment by fmvilas** [comment]
Absolutely! Go ahead!
