### ISSUE TITLE
Add docs on how Glee works

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#206]
It would be awesome to have docs explaining how Glee works. These docs should be mainly targeted at contributors or potential contributors.

**Comment by fmvilas** [comment]
Still relevant, don't stale it :)

**Comment by octonawish-akcodes** [comment]
I can work on this @fmvilas can you guide a bit more

**Comment by Souvikns** [comment]
@octonawish-akcodes if you are working on this, and you are stuck feel free to ask your doubts

**Comment by octonawish-akcodes** [comment]
@Souvikns can you provide any pointers and resources to look into it and should I also have to include a diagrammatical workflow?

**Comment by Souvikns** [comment]
To begin, it would be beneficial for you to familiarize yourself with the glee project. I recommend that you explore the examples in the [examples folder](https://github.com/asyncapi/glee/tree/master/examples) and attempt to create something on your own using glee. By doing so, you will gain a deeper understanding of the functionality and capabilities of glee. 

@octonawish-akcodes also feel free to ask if you have a problem understanding something or you have some doubts.

**Comment by cristianvasquez** [comment]
Hi!, the links to the documentation about how Glee works point to 404 (Readme.md)
