### ISSUE TITLE
feat: expose (isomorphic) API to consume AsyncAPI doc and generate server/client dynamically 

### ISSUE THREAD

**Issue by miguelrk** [asyncapi/glee#223]
> From slack [thread](https://asyncapi.slack.com/archives/CQVJXFNQL/p1641260134486000)

I've been looking for a tool to dynamically/programatically consume OpenAPI specs to generate javascript/typescript clients, but most tools seem to be CLIs that output the full server and/or client code after running a command line operation.

For illustration purposes, I'm thinking about an API something like the following:
```javascript
const asyncApiDoc = {...}
const { client, server } = openapi.consume(asyncApiDoc)
client.receive((data) => console.log(data))
client.receive('/path/here', (data) => console.log(data))
client.send('/path/here', {...})
```
The required protocols can be easily parsed from the AsyncAPI document and clients/servers instantiated at runtime (assuming there is a valid JS/TS implementation for them).

Ideally, the API will abstract protocols away and allow communicating (send/receive) with the API via a single API.

It is more of an SDK rather than a CLI. Protocol bindings should ideally be external to the core implementation and thus be progressively added (e.g. for WebSockets, MQTT, HTTP, Kafka, ...).

**Comment by miguelrk** [comment]
According to comments in [this slack thread](https://asyncapi.slack.com/archives/CQVJXFNQL/p1641260134486000), Glee already implements the functionality to generate clients and servers internally. 

Some discussed options for making client/server generation code available for dynamic generation of clients/servers were:

1. Export to standalone (isomorphic) library and publish as npm package, for Glee to consume as dependency
2. Expose client/server generation code within the Glee framework, to be consumed as a library (no additional package)

Useful comments by @fmvilas:
- this functionally is somehow baked into Glee right now
- so far, Glee can generate MQTT clients and WebSocket servers
- making this isomorphic will be very difficult
- still, only HTTP and WebSocket clients are usually used

**Comment by miguelrk** [comment]
Just to keep track, here are some runtime libraries (not codegen) which allow dynamic client creation within JS/TS for OpenAPI:
- [anttiviljami/openapi-client-axios](https://github.com/anttiviljami/openapi-client-axios)
- [ninofiliu/oa-client](https://github.com/ninofiliu/oa-client)

Something similar is what I was intending for AsyncAPI with this issue, here an example from openapi-client-axios:
```javascript
import OpenAPIClientAxios from 'openapi-client-axios'

const api = new OpenAPIClientAxios({ definition: 'https://example.com/api/openapi.json' })
api.init()

async function createPet() {
  const client = await api.getClient()
  const res = await client.createPet(null, { name: 'Garfield' })
  console.log('Pet created', res.data)
}
```

**Comment by fmvilas** [comment]
And in a similar fashion but from the server point of view: https://github.com/anttiviljami/openapi-backend.

**Comment by fmvilas** [comment]
@miguelrk would you be willing to open a PR for this issue? I'm happy to guide you as needed.

**Comment by miguelrk** [comment]
Yes! I'd be glad to, just need to finish some other stuff first. Mind keeping this open for a while? 😀

**Comment by fmvilas** [comment]
Yeah, I can work on other stuff first. I'm actually adding tests now so it may help you refactor the code too.

**Comment by fmvilas** [comment]
@miguelrk are you still interested in contributing this?

**Comment by fmvilas** [comment]
I think it's still an interesting concept to explore. Maybe someone else wants to pick it up?
