### ISSUE TITLE
Support different asyncapi file names: asyncapi.json and asyncapi.yml

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#23]
#### Reason/Context
Some people are using the JSON format of AsyncAPI or they name their files as `asyncapi.yml` (notice the `.yml` instead of `.yaml`).

#### Description
It would be awesome if Glee could auto-detect that you're using one of those files. It could also complain when you use many of them at the same time. For instance, if it finds `asyncapi.yaml` and `asyncapi.json`.

**Comment by magicmatatjahu** [comment]
Maybe should be labelled with `good first issue`?

**Comment by fmvilas** [comment]
Keeping it open for now. It's something that needs to be done at some point.

**Comment by sudoshreyansh** [comment]
Does this issue need any more work ?

**Comment by fmvilas** [comment]
There's a PR from @panwauu: https://github.com/asyncapi/glee/pull/146. Did a review a while ago but he doesn't respond. Let's give him some more days and if he doesn't respond we can move it forward.
