### ISSUE TITLE
Making testing easier with Glee

### ISSUE THREAD

**Issue by sudoshreyansh** [asyncapi/glee#255]
#### Reason/Context
To test Glee applications, developers have to either rely on 3rd party tools or write their tests. This could be hugely simplified if Glee shipped with automated testing features.

#### Description
Developers would write tests within a Glee project in a separate directory. While writing tests, developers should only focus on the message being sent to the server and the response provided by the server or the actions the server does. Everything else would be handled by Glee. 

There could be multiple options in the command for specifying the type of test to run. Also, snapshots could be saved for future snapshot testing if specified by the user.

**Comment by sudoshreyansh** [comment]
@fmvilas please add the gsoc label to this issue.

I want to work on this idea in GSoC.

**Comment by fmvilas** [comment]
Done! Thanks a lot for taking the time to create it 🙏

**Comment by ritik307** [comment]
@fmvilas I would like to work on this issue. 😊
