### ISSUE TITLE
Add support for Kafka

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#256]
#### Reason/Context

Currently, Glee only supports WebSockets (server) and MQTT protocols. This means it's unusable for those using Kafka, AMQP, or any other different protocol.

#### Description

We should add support for Kafka. In theory, it should be just a matter of adding a new adapter in [the `adapters` folder](https://github.com/asyncapi/glee/tree/master/src/adapters). However, we should also take into account that Kafka supports exactly-once semantics (unlike MQTT and WebSockets) and, therefore, it may be a good idea to address #27 first, although not required.

#### References

* https://www.baeldung.com/kafka-exactly-once
* https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/

**Comment by Ruchip16** [comment]
@fmvilas Would like to work on this issue as a part of the Mentorship program

**Comment by fmvilas** [comment]
This is cool! This is an important one! Good choice :)

We'll wait until June 6 to announce the candidates but in the meantime feel free to ask any questions you may have. Good luck! 🤞

**Comment by Ruchip16** [comment]
Sure, hoping for the best meanwhile would check the references attached above to get a more detailed understanding of the issue.

**Comment by fmvilas** [comment]
Congratulations @Ruchip16 for being selected for the AsyncAPI Mentorship program to work on this issue 🎉 I knew it was a good choice 😄 I'll be sending DM to you on Slack so we can start working on it when it's best for both.

**Comment by Ruchip16** [comment]
sureee suree cant wait to dive deep into the issue

**Comment by fmvilas** [comment]
We're working on it dear bot. Don't close it :)

**Comment by fmvilas** [comment]
It's already there! #342 Closing the issue.
