### ISSUE TITLE
Add support for AMQP 0-9-1

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#257]
#### Reason/Context

Currently, Glee only supports WebSockets (server) and MQTT protocols. This means it's unusable for those using Kafka, AMQP, or any other different protocol.

#### Description

We should add support for AMQP 0-9-1. In theory, it should be just a matter of adding a new adapter in [the `adapters` folder](https://github.com/asyncapi/glee/tree/master/src/adapters).

**Comment by likitarai1** [comment]
Hi @fmvilas I would like to work on this issue as a part of the Mentorship program.

**Comment by fmvilas** [comment]
Awesome! If you have any questions meanwhile we decide which issues/people get selected for the mentorship program, let me know. Happy to answer them 🙂

**Comment by likitarai1** [comment]
I was looking into the adapters folder just now to understand the issue in depth. If you could share some more details or references it would be a great help.

**Comment by fmvilas** [comment]
I think this is a great read to start with: https://www.rabbitmq.com/protocol.html.

**Comment by likitarai1** [comment]
When will the selected issues be announced?

**Comment by fmvilas** [comment]
6th of June: https://github.com/asyncapi/community/discussions/284#discussioncomment-2508121

**Comment by fmvilas** [comment]
@likitarai1 in the end this issue wasn't selected for the mentorship program. Do you want to contribute it?

**Comment by likitarai1** [comment]
@fmvilas I want to contribute but I feel it's too complex for me right now. Would try to start from basics, get familiar with AsyncAPI and in future if the issue is still open, might even work on this.

**Comment by fmvilas** [comment]
Fair. In any case, if you need help, I'm currently running meetings with some other folks to help them get familiar with Glee and AsyncAPI. Reach out to me on Slack if you want to be invited.

**Comment by KhudaDad414** [comment]
we still need this.
