### ISSUE TITLE
Add support for AMQP 1.0

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#258]
#### Reason/Context

Currently, Glee only supports WebSockets (server) and MQTT protocols. This means it's unusable for those using Kafka, AMQP, or any other different protocol.

#### Description

We should add support for AMQP 1.0. In theory, it should be just a matter of adding a new adapter in [the `adapters` folder](https://github.com/asyncapi/glee/tree/master/src/adapters). Beware AMQP 1.0 and AMQP 0-9-1 are totally different protocols, despite having the same name.

**Comment by atharvagadkari05** [comment]
@fmvilas I would like to work on this issue under the GSOC tag. I want to discuss some of the things which will just clarify my doubts even further.

**Comment by atharvagadkari05** [comment]
The `adapter` folder has two different files for `ws` and `socket.io`. Do we have to make two different files for AMQP and RabbitMQ for the integration?

**Comment by fmvilas** [comment]
No, since RabbitMQ uses AMQP 0-9-1, this is something to be implemented in #257.

**Comment by atharvagadkari05** [comment]
Great to be back at this issue. I've already started working on this issue.
Do I have to explain how I'm gonna execute this, here?
@fmvilas @derberg

**Comment by fmvilas** [comment]
No, you don't have to but feel free to share as much information as you want. Please, bear in mind we'll decide on the list of candidates by June 6th so I would not work on this in the meantime.

**Comment by atharvagadkari05** [comment]
@fmvilas Is this issue still open for work?
 I was unable to make it through the mentorship program can I still work on this issue???

**Comment by atharvagadkari05** [comment]
I'm kinda stuck on this issue, don't know where to start. Can anyone guide me for the same?

**Comment by fmvilas** [comment]
@atharvagadkari05 I'm happy to guide you. I'll ping you after August 15th, I'm going on holiday now.

**Comment by fmvilas** [comment]
I'm back now, @atharvagadkari05. How can I help you? Where are you stuck? Would be awesome if you can share some code (if you have it) or provide a detailed explanation of why/where are you stuck. Happy to jump on a call if needed.

**Comment by atharvagadkari05** [comment]
Thanks for the reply @fmvilas 👍. I haven't written any code, I was just reading about different protocols (AMQP and its versions).
As you mentioned I checked the `adapter` folder and different files (MQTT and socketio). I just need to know where I can start and what to do further. It would be fantastic if you could guide me to some sources(Blogs, Docs). 

Once I know what to do I can proceed with my work 👍.

**Comment by fmvilas** [comment]
@atharvagadkari05 I'm doing a Glee codebase onboarding session tomorrow at 4 PM CEST. Do you want to join?

**Comment by atharvagadkari05** [comment]
@fmvilas Sure 👍

**Comment by atharvagadkari05** [comment]
@Souvikns @fmvilas  I think I've found the official documentation for the AMQP JavaScript client (Rhea) 
https://access.redhat.com/documentation/en-us/red_hat_amq/7.0/html-single/using_the_amq_javascript_client/index
Can you please confirm?
Also, I'm planning to open a draft PR so that you can track my progress.

**Comment by fmvilas** [comment]
This is not the official rhea docs AFAIK. This is just an RH library making use of rhea if I understood correctly.

**Comment by kaushik-rishi** [comment]
I'm picking this up with @KhudaDad414 permission.

**Comment by AceTheCreator** [comment]
> I'm picking this up with @KhudaDad414 permission.

I don't think that will be necessary, as there's already a PR for it, #456

**Comment by KhudaDad414** [comment]
@AceTheCreator amqp 0-9-1 and amqp 1 are two different protocols for some reason. 😆

**Comment by AceTheCreator** [comment]
I'm so sorry; I thought it was the same issue

**Comment by KhudaDad414** [comment]
Still relevant.
