### ISSUE TITLE
Add support for clusterization

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#26]
#### Reason/Context
Currently, Glee would not behave great when spanning multiple instances. The reason is the [`broadcast`](https://github.com/asyncapi/glee/blob/master/docs/functions.md) option. As it is right now, we're storing connections in memory, so when a function responds saying it wants to broadcast a message, it goes through all the connections and sends the message. Obviously, if we have multiple instances, the message will be "broadcasted" only to a subset of clients (the ones that a given instance has in memory).

Relevant parts of the code are:

* https://github.com/asyncapi/glee/blob/master/src/lib/adapter.js#L23
* https://github.com/asyncapi/glee/blob/master/src/lib/adapter.js#L69
* https://github.com/asyncapi/glee/blob/master/src/lib/adapter.js#L82
* https://github.com/asyncapi/glee/blob/master/src/lib/adapter.js#L36

#### Description
We should allow for clusterization of the multiple instances. There are multiple approaches for this but I think the simplest one would be to keep things in memory and let the user choose a mechanism to communicate the different instances, e.g., Redis.

It would be something like:

1. A message with the broadcast option enabled is requested to be sent.
2. The adapter sends a message to Redis saying it wants to broadcast a message.
3. All the instances receive the message and proceed to send it.

The advantage of this approach is that it's simple but it doesn't guarantee all the messages will be sent. For instance, what happens if one of the instances doesn't receive the Redis message? That's something to think about. There are many existing techniques, we don't need to reinvent the wheel.

**Comment by sudoshreyansh** [comment]
I would like to work on this issue.

**Comment by fmvilas** [comment]
Awesome, @sudoshreyansh! Go ahead with it. Is there anything I can do to help you? Happy to help here or in [our Slack workspace](https://www.asyncapi.com/slack-invite).
