### ISSUE TITLE
Add support for HTTP servers and clients

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#260]
#### Reason/Context

Currently, Glee only supports WebSocket and MQTT protocols. That makes it unusable for someone wanting to use any other protocol, like HTTP.

#### Description

Glee should be able to create an HTTP server (API) or a client out of an AsyncAPI definition. We can probably use the same `x-kind` extension defined in #259, as a way to understand when we want a client and when we want a server.

One key part of this issue is to actually work on the [HTTP binding](https://github.com/asyncapi/bindings/tree/master/http). Especially, in this issue about [adding support for multiple methods](https://github.com/asyncapi/bindings/issues/2).

**Comment by AMorgaut** [comment]
To me there is a specific usage of HTTP that totally makes sense for AsyncAPI and which is not WebSocket

I'm thinking about [EventSource ](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) aka "Server-Sent Events" which is typically event-based

**Comment by fmvilas** [comment]
That's a good point, @AMorgaut. I don't think it should be separated. We should aim for full HTTP support IMHO.

**Comment by deepanshu44** [comment]
Hello @fmvilas , I just want to ask that should I work on this issue? Is it difficult to solve this issue? 
Thanks

**Comment by Souvikns** [comment]
@fmvilas by client do you mean glee server will make a API call to the client server as per the bindings information and the data that is returned from `operationId` function?

**Comment by fmvilas** [comment]
Nope. I mean Glee should behave like a client not like a server. It should make calls to some APIs but it shouldn't be a server itself.

**Comment by Souvikns** [comment]
> Nope. I mean Glee should behave like a client not like a server. It should make calls to some APIs but it shouldn't be a server itself. 

🤔 Kinda confused, I should be able to create a http REST API with glee if I want right, so like I would make an API call to glee through http and get a response. Would you call it a server?

**Comment by fmvilas** [comment]
Yeah sorry, somehow I got confused by your question too. What I mean is that Glee should behave in two different ways, depending on how you configure your AsyncAPI document:

1. As a server: this would, for instance, leverage ExpressJS or something similar behind the scenes. This is for people who want to create a REST API.
2. As a client: this would let you make calls to **other** REST APIs. Say, for instance, every time you receive a message via MQTT you want to call a 3rd-party REST API. That should be possible too.

Note that a Glee application may be a mix of both, a client and a server. For instance, imagine we want to create a REST API, and every time the user does `POST /users` we want to call an external service, e.g., the Google Analytics API, another API in our system, etc.

Does that make sense?

**Comment by ritik307** [comment]
Hi, @fmvilas I would like to work on this issue. So can you kindly help me out in figuring out where to start? Like should I start making REST APIs or some other approach? 😊

**Comment by Souvikns** [comment]
Hey, @ritik307 I was working on this issue and made some progress as well https://github.com/asyncapi/glee/pull/265, since we need to update the bindings I am focusing on that right now https://github.com/asyncapi/bindings/pull/131. I would love to mentor you (if you want me as a mentor) if this idea gets issue gets selected.

**Comment by ayushpaharia** [comment]
Hello @Souvikns Can you give some context on this issue. I'm interested in working on this as a Mentorship project

**Comment by Souvikns** [comment]
So I will be mentoring this issue if it gets selected 😄 . To answer both @ayushpaharia and @ritik307 you should start getting familiar with glee and its codebase. I would suggest you fork and play around with glee. look into the examples folder to get a better understanding of how glee is working. Secondly, start reading the codebase and tweaking some code here and there to get a feel of things. 

Also, check out https://github.com/asyncapi/glee/pull/265, and even review it. You guys can also join the https://github.com/asyncapi/community/issues/352 meeting for understanding how the HTTP binding will shape up. Lastly, feel free to ask any questions you have here or on slack.

**Comment by ritik307** [comment]
@Souvikns Will surely start exploring the glee. 😄

**Comment by ayushpaharia** [comment]
#265 -  Looks interesting. I'll get started with playing around with glee. See you in [asyncapi/community/#352](https://github.com/asyncapi/community/issues/352) :100: @Souvikns

**Comment by ritik307** [comment]
@Souvikns I will be more than happy to be mentee for the mentioned issue 😁. Thank you so much for providing me the opportunity.🥳

**Comment by Souvikns** [comment]
@fmvilas can you please reopen this, as it is being currently worked on https://github.com/asyncapi/glee/pull/320
