### ISSUE TITLE
Automatically generate docs

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#261]
#### Reason/Context

When describing the benefits of a spec-driven framework like Glee, I'm always mentioning the fact that we could have docs and code always in sync. However, we're not generating any docs, we're leaving this responsibility to the user, which kinda breaks the purpose 😅 

#### Description

We should provide a way to automatically generate docs. Here are the ways that come to my mind:

1. Start an HTTP static server and serve the docs there. For instance, `http://localhost:3000/docs` would show the docs. Fully configurable from the glee.config.js file.
2. Generate docs in a folder inside the project. Fully configurable from glee.config.js file, like the path to the folder and the Generator template to use. We can default to `docs` and the https://github.com/asyncapi/markdown-template/.
3. A Github Action (maybe Gitlab CI too?) that calls a webhook URL (or multiple ones?) to update external systems, like developer portals. E.g., a POST call to a URL containing the AsyncAPI definition. This should be a separate package though.

**Comment by likitarai1** [comment]
I would like to create a GSoC proposal on this issue.

**Comment by AceTheCreator** [comment]
@fmvilas since GSOC rejected us this year, I guess I should just work on this issue. I need to get familiar with glee very well cuz I'll be using it as an example of one of the amazing tools the AsyncAPI community is building during my talk at Osca fest later this month.

**Comment by fmvilas** [comment]
Yeah go ahead mate :+1:

**Comment by AceTheCreator** [comment]
Yo @fmvilas, now I have the time to start contributing to this project. LOL

Wanna confirm when you say docs, do you mean the AsyncAPI docs?

**Comment by fmvilas** [comment]
Yeah, leverage Generator to generate HTML or markdown docs.

**Comment by Sihamtahi** [comment]
Hi, I want to work on this issue for the GSOC . I am working in my internship on the automatic generation of a formalism-b to java. I want to take the challenge with the AsyncAPI documentation too

**Comment by fmvilas** [comment]
Awesome, @Sihamtahi! @AceTheCreator did you start working on the issue already? If this issue gets selected for the Mentorship program and @Sihamtahi is selected as well, maybe you can mentor her. How does that sound? I hope it's not too late and you have the code running in your machine 😄

**Comment by AceTheCreator** [comment]
I've started working on it already and I think I'm almost done, I didn't know it's part of the mentorship program. @fmvilas what do I do? 😂 @Sihamtahi can you pick another issue and I'm willing to help you

**Comment by Sihamtahi** [comment]
Hello @fmvilas @AceTheCreator this is brilliant 😂😂. Yes, in fact, I have commented in other issues. So, if i was selected i will contact you. 
Thank you 🙏

**Comment by fmvilas** [comment]
Perfect! I'm removing the `gsoc` label to avoid confusion.

**Comment by AceTheCreator** [comment]
Hey, @fmvilas any idea why I'm getting this error while trying to build the package?
![23 05 2022_13 56 03_REC](https://user-images.githubusercontent.com/40604284/169824479-c4e50638-0a12-4979-9fd6-d7b21e42da03.png)

**Comment by fmvilas** [comment]
Uh! 🤔 I have no idea. I'm not getting this error. Check the Typescript version just in case.

**Comment by fmvilas** [comment]
@AceTheCreator in the end, I also faced this issue and got a fix for it: https://github.com/asyncapi/glee/pull/326.
