### ISSUE TITLE
Add support for retries, backpressure, and at-most-once, at-least-once, and exactly-once semantics

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#27]
#### Reason/Context
There are many points in the existing codebase that can lead to lost messages.

#### Description
We should review and identify which parts of the codebase can cause problems and fix them. We should be looking for:

1. Retries. What if calling a function fails? Especially when we implement the HTTP runtime. We should be retrying and letting the user configure how to do it.
2. Backpressure. What happens if a client/broker starts sending too many messages too quickly? We should be able to control the number of messages per second we want to receive, telling the client/broker to slow down. This is not always possible but definitely should be implemented for those protocols that provide a mechanism for that.
3. At-most-once, at-least-once, and exactly-once semantics. We should be able to guarantee that a message is going to be received either at most once, at least once, or exactly once. Some protocols don't have a mechanism for that so we should focus on those that have it.

**Comment by fmvilas** [comment]
Dear bot, keep this issue open because we still need to work on it.

**Comment by ritik307** [comment]
@fmvilas @derberg I would like to work on this as part of the Mentorship program. 😊

**Comment by sudoshreyansh** [comment]
Hi, I would like to work on this as a part of the mentorship program, if it gets selected.

**Comment by abhishek-iiit** [comment]
Hi @fmvilas, I would love to contribute to this Project under AsyncAPI Mentorship. I did gone through the issue and I believe under your/mentor guidance and support, I can be able to make it and lead it to a success.

Looking forward and making out plans to execute to this project :)

**Comment by fmvilas** [comment]
Congratulations @sudoshreyansh for being selected for the AsyncAPI Mentorship program to work on this issue 🎉

**Comment by sudoshreyansh** [comment]
Thanks @fmvilas !

**Comment by fmvilas** [comment]
Dear bot, don't mark it as stale, it's in the works right now.

**Comment by KhudaDad414** [comment]
@sudoshreyansh Hey mate, does #323 resolves this issues? 🤔

**Comment by fmvilas** [comment]
No, it doesn't. #323 is definitely a step forward but this issue should go beyond MQTT.
