### ISSUE TITLE
[Docs Bug 🐞 report]: Functions `broadcast` option is still in the docs

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#271]
### Describe the bug you found in AsyncAPI Docs.

Functions documentation shows that we can use the `broadcast` key in the returned object but that's not the case anymore.

### Attach any resources that can help us understand the issue.

Scroll down to the table in the [Functions docs](https://github.com/asyncapi/glee/blob/master/docs/functions.md) where there are three options listed: send, reply, broadcast. We should get rid of `broadcast`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pratik2315** [comment]
Hey @fmvilas ! Can I work on this issue if its alright with you ?

**Comment by fmvilas** [comment]
Absolutely! Go ahead 🙂
