### ISSUE TITLE
Switching to `node-ipc` altenatives

### ISSUE THREAD

**Issue by achrinza** [asyncapi/glee#275]
#### Describe the bug

Currently, this framework has a [direct dependency on `node-ipc@^10.0.1`](https://github.com/asyncapi/glee/blob/2b2fb5455c034f73851afe9781d73c9116084155/package.json#L54). Considering the recent developments of the `node-ipc` maintainer [publishing malicious versions](https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/), are there any plans to switch to a fork?

Currently, the published versions now only have a harmless `peacenotwar` protestware dependency.

Depending on the threat model, pinning to a known-good version of `node-ipc` may not be suffice as there are nested, transitive dependencies which are maintained by the same person. Hence, it may be possible for the same maintainer to publish a malicious version of `easy-stack`, `vanilla-test`, `ansi-colors-es6` or `strong-type`.

#### How to Reproduce

Installing the latest version of `glee` installs transitive dependencies managed by the @/riaevangelist.

#### Expected behavior

Switch to a clean fork of `node-ipc`.

Some available forks that I'm aware of:

- [`@achrinza/node-ipc`](https://github.com/achrinza/node-ipc/issues/1) - My own fork
- [`@node-ipc/node-ipc`](https://github.com/node-ipc/node-ipc) - Another fork with new features

**Comment by jonaslagoni** [comment]
The dependency is leftover from earlier implementation, it's getting removed: https://github.com/asyncapi/glee/pull/274
