### ISSUE TITLE
Introduce project type configuration

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/glee#31]
#### Reason/Context
It would be great to know exactly what project type, glee is executing. That way it knows what runtime to run and what extra functionality it needs to perform.

#### Description
I suggest we add something similar to what the generator has for [nunjucks and react](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file) called `renderer`, here maybe `type` makes sense? 🤔 

As a side-effect, I suggest we remove the experimental flag for using the java runtime as we then explicitly tell it to use the new configuration.

**Comment by fmvilas** [comment]
Agree to remove the env variable. This is not something that changes from one environment to another 👍 

However, I'd introduce a similar concept in the config file. Something like:

```js
{
  experimental: {
    runtime: 'java'
  }
}
```

Once `runtime` is not an experimental feature anymore, we take it out. However, if a given runtime is still experimental, you'd have to enable it explicitly. For instance:

```js
{
  runtime: 'python',
  experimental: {
    runtimes: {
      python: true,
    }
  }
}
```

or even


```js
{
  runtime: 'python',
  experimental: {
    runtimes: {
      python: {
        enabled: true,
        extensions: ['.py', '.py2', '.py3'], // Just so we can add other options to the runtime
      },
    }
  }
}
```

**Comment by fmvilas** [comment]
Following with the Python example, we may also want to consider something like:

```js
{
  runtimes: {
    java: {
      enabled: true,
    }
  },
}
```

This would be once the feature is not experimental.

**Comment by fmvilas** [comment]
@jonaslagoni do you still want to work on this?

**Comment by jonaslagoni** [comment]
Yes, if I had more hours in the day 😆 For now I can't dedicate the effort necessary to push glee further,🤞in the new year.

**Comment by fmvilas** [comment]
Closing as it's not relevant anymore. We decided to remove runtimes on #207.
