### ISSUE TITLE
How to stop a loop in a lifecycle events?

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#325]
#### Reason/Context
So according to https://github.com/asyncapi/glee/blob/master/docs/lifecycle-events.md we can create lifecycle events and bind them to an event, Now we do have examples where we create loops to stream a series of data, How do we stop this loop say to react to any other event since I can only subscribe to only one event I have no way terminate the loop say any other event occurs or my client connection is interrupted. 

#### Description
Let me take a particular example to showcase the problem. 

Suppose I have this Lifecycle function, which is subscribed to the event `onServerConnectionOpen`, which means this function starts to run when a successful connection is established, But when the connection is terminated before the loop ends the loop keeps on running, and there is no way to stop the loop. 

```ts
import dummyjson from 'dummy-json'
import { Message } from '@asyncapi/glee'

export default async function ({ glee, connection }) {
  (function myLoop(i) {
    setTimeout(() => {
      glee.send(new Message({
        channel: '/travel/status',
        connection,
        payload: generateResponse()
      }))
      if (--i) myLoop(i)
    }, 1000)
  }(100))

  function generateResponse() {
    const template = `{
      "destination": "{{city}}",
      "arrival": "{{int 2 6}}h",
      "distance": "{{int 18 65}}km"
    }`
    return JSON.parse(dummyjson.parse(template))
  }
}

export const lifecycleEvent = 'onServerConnectionOpen'
export const channels = ['/travel/status']
```

**Comment by KhudaDad414** [comment]
Based on my knowledge of Node.js I don't think it is possible. Node is single-threaded and it's not like we can run the user's code in another thread and kill it whenever we want. (Maybe someone with a deep knowledge of Node.js has a way of doing it 🤔 )  besides, I don't think it is our job to prevent users from writing infinite loops. 🤷

**Comment by oviecodes** [comment]
@Souvikns @KhudaDad414 , I'm yet to understand how Glee lifecycle works but from the code snippet above, it'll be nice to have a connection status, that could be checked in order to terminate a loop once the connection ends.
