### ISSUE TITLE
Not possible to connect to MQTT server when launching glee app

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/glee#357]
#### Describe the bug
I'm not able to to connect to an MQTT server (located in a docker container) when trying to launch my glee app.

#### How to Reproduce

- Execute `npm run dev` in a glee project containing the _asyncapi.yaml_ and _.env_ files shared [here](https://gist.github.com/peter-rr/c068c5d67b7223c4c18de489746dcd50).

- URLs tested in `servers/development/url` at asyncapi file: `0.0.0.0:1883`, `127.0.0.0:1883`, `localhost:1883`, `mqtt://test.mosquitto.org:1883`

- Output displayed on the terminal:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/81691177/201172626-03dcffc7-8edb-49cb-9fa9-2aba70d6d07a.png">

#### Expected behavior
The connection with the MQTT server should be established with no errors displayed on the terminal.

**Comment by KhudaDad414** [comment]
the weird thing is that it works fine with `mqtt://test.mosquitto.org` but it fails when I specify the port 🤔
