### ISSUE TITLE
[📑 Docs]: Improve content under Functions section on Glee documentation

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/glee#358]
### What Dev Docs changes are you proposing?

I would propose to include some information about `subscribe` operations under [Functions section on Glee documentation](https://github.com/asyncapi/glee/blob/master/docs/functions.md).

From my point of view it's pretty clear how Glee interacts with `publish` operations. However, at the time of building a Glee project I've been wondering what happens then with `subscribe` operations and their corresponding function files, and some questions came to my mind:

- Should I include the function files from `subscribe` operations in the Glee functions folder as well? Or should I include only the ones from `publish` operations?
- Are the functions related to `subscribe` operations not necessary for Glee as they are not mentioned at all?
- Why some Glee examples include the `operationId` attribute for `subscribe` operations? Is it necessary at some point or just ignored by Glee? I found it a bit confusing 🤔 

This is the specific part of the document where I think that info about the functions from `subscribe` operations might be included:
![image](https://user-images.githubusercontent.com/81691177/201409177-383928eb-d261-4012-bff1-25faa7c4e37b.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by fmvilas** [comment]
Yeah, it's a bit awkward but the reasoning is that `subscribe` in AsyncAPI means that your app is sending a message. The `functions` folder is there for reacting to the messages received instead. The messages sent by your app must be defined as part of a [lifecycle event](https://github.com/asyncapi/glee/blob/master/docs/lifecycle-events.md) or as a response to one of the functions in the `functions` folder.

So, to answer your questions:

> Should I include the function files from subscribe operations in the Glee functions folder as well? Or should I include only the ones from publish operations?

Only the `publish` ones.

> Are the functions related to subscribe operations not necessary for Glee as they are not mentioned at all?

They are not needed so far but it's a good point. Might be worth exploring making it work in a different way.

> Why some Glee examples include the operationId attribute for subscribe operations? Is it necessary at some point or just ignored by Glee? I found it a bit confusing 🤔

That's definitely confusing. They are not needed at all so they shouldn't be there to avoid confusion.

**Comment by octonawish-akcodes** [comment]
can i work on this

**Comment by fmvilas** [comment]
@octonawish-akcodes absolutely 👍 Feel free to give it a try.
