### ISSUE TITLE
[📑 Docs]: Improve content under Application Structure on Glee documentation

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/glee#359]
### What Dev Docs changes are you proposing?

I would propose to add some specific clarification about the `asyncapi.yaml` file under [Application Structure section on Glee documentation](https://github.com/asyncapi/glee/blob/master/docs/app-structure.md).

Basically, I think It might be useful to clarify the `asyncapi.yaml` file name must not be changed since you can easily make the same mistake I did by replacing the file name with the name of my service (e.g. "managemet_service.yaml"), making the Glee app not working at all.

![image](https://user-images.githubusercontent.com/81691177/201422559-a106ac4a-acec-4f98-8c27-e1e4b2be541b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmvilas** [comment]
@octonawish-akcodes yeah go ahead and give it a try 👍
