### ISSUE TITLE
[Docs Bug 🐞 report]: Wrong variable name under Lifecycle Events on Glee documentation

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/glee#360]
### Describe the bug you found in AsyncAPI Docs.

I'd like to report a bug I found in a code snippet under [Lifecycle Events on Glee documentation](https://github.com/asyncapi/glee/blob/master/docs/lifecycle-events.md#restricting-the-lifecycle-event).

### Bug description
In case we want to restrict the lifecycle event by channel/topic, the variable name we are suggested to use should not be `servers` as we can see in the code snippet at the bottom.

### Expected output
We should use the variable name `channels` instead, so the line to be added would be as follows:
`export const channels = ['user/signedup']`

### Attach any resources that can help us understand the issue.

![image](https://user-images.githubusercontent.com/81691177/201770487-89cfeba0-13cc-40b4-8b7b-5eb73a8c8365.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ItsRoy69** [comment]
If the issue has been fixed then can someone close this ?
