### ISSUE TITLE
Where should we store examples?

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#365]
#### Reason/Context
I think examples are one of the useful resources that we currently have regarding the glee project. they have helped me and I am sure they are useful to others as well.
Currently, we store the example projects that have been developed with glee under the `examples` folder which is not great from a maintainability point of view. besides, it locks that example in the glee repo and makes it harder to make changes to the examples.

I think there are two options that we have when it comes to handling examples.

#### 1. Using Submodules
Each one of the contributors can create a repo for their examples and we can link them here using git submodules in the examples folder.

#### 2. Linking them in the project's README.
creating repos for each example and linking them in the main README file. most of the other projects are doing this and I think it is the most sensible way of handling examples.

cc: @fmvilas @Souvikns

**Comment by fmvilas** [comment]
Is it really a problem though? I see [Next.js has it in the `examples` folder](https://github.com/vercel/next.js/tree/canary/examples) and they get many more contributions than Glee 😅
