### ISSUE TITLE
Error when the server is not specified

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#371]
https://github.com/asyncapi/glee/pull/272 had the side effect of specifying `server` in `send` messages mandatory.
I mean this worked with previous versions:
```
{
  send: [{
    payload: 'my message'
  }]
}
```
but now it gives:
```
x Cannot read property 'protocol' of null
    at file:///Users/khudadad/Projects/asyncapi/glee/dist/lib/functions.js:107:73
    at Array.forEach (<anonymous>)
    at file:///Users/khudadad/Projects/asyncapi/glee/dist/lib/functions.js:105:111
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/khudadad/Projects/asyncapi/glee/dist/lib/functions.js:4:58)
```

and I have to specify the server even if there is only one server:
```
{
   send: [{
      server: 'websockets',
      payload: 'my message'
  }]
}
```
If this was intentional, we need to update the docs and show better error messages.
I think we need to implement some kind of fallback to the default server if there is only one server. 🤔 

cc: @Souvikns

**Comment by Souvikns** [comment]
when you do `send` you have to specify the server name, but when you use `reply` you do not need to pass the server name.
