### ISSUE TITLE
support for both js and ts file for glee config

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#375]
#### Reason/Context

Currently, glee only accepts `glee.config.js` file type for config, for IntelliSense purposes it should also accept `glee.config.ts`. It should give typescript file preference over javascript file. 

https://github.com/asyncapi/glee/blob/4f6b51a70171a80afb594ce296e4aee3d5fe6497/src/lib/configs.ts#L23

Currently, it is hardcoded, we basically have to check which file type is present in the working directory and then load the respective file.

**Comment by magicmatatjahu** [comment]
Those who will be working on it should see how TS is handled in the `jest.config.ts` by JEST.

**Comment by Jittojoyes98** [comment]
Anyone working on this isuue?
