### ISSUE TITLE
[📑 Docs]: Improve content under Lifecycle Events on Glee documentation

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/glee#387]
### What Dev Docs changes are you proposing?

I would propose to include more specific information about the required `async function` under [Lifecycle Events section on Glee documentation](https://github.com/asyncapi/glee/blob/master/docs/lifecycle-events.md#lifecycle-events).

From my point of view, the attributes of the object that the function takes as an argument are just briefly defined but the type of each attribute or how many of them should be used is not specified, and therefore it's not clear enough how to work with them.

Here is where the info I'm missing might be included:

![image](https://user-images.githubusercontent.com/81691177/221633167-831101ec-c005-4a0c-8d0e-5d45a0192b4f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peter-rr** [comment]
Still relevant.

**Comment by peter-rr** [comment]
@KhudaDad414 Do you think this is still relevant considering the [updated documentation](https://github.com/asyncapi/glee/blob/master/docs/pages/function-lifecycle-events.md#list-of-events)? 🤔

**Comment by KhudaDad414** [comment]
@peter-rr Since we going to make some [big changes](https://github.com/asyncapi/glee/issues/795) to how it works, I think we can close this issue safely.

**Comment by peter-rr** [comment]
Makes sense! 🚀
