### ISSUE TITLE
Integrage Modelina to provide type safety for message payloads in functions

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#391]
### Reason/Context
One of the challenges I face when using Glee is the uncertainty of the values in message payloads. Seeing the "any" type in Typescript can also be a bit intimidating. 😆 

However, AsyncAPI provides a helpful feature that allows us to describe the message payload format using JSON Schema. With the use of https://github.com/asyncapi/modelina, we can conveniently convert these schemas into Typescript Types.

#### Step 1
Use Modelina and generate the types from the AsyncAPI file. Categorize the message payload type by the `operationId`. for example we can have `types/operations/hello.d.ts` for `hello` operation in `.glee` folder.
It would be great for this file to contain the whole `function` type so it can be easily used in `hello.ts` function.

#### Step 2
When we generate a Glee project for an AsyncAPI file, Glee should create empty blueprints for all of the operations and assign the correct types to them. this way, user can start with the blueprint and get all of the type safety and suggestions for their message payloads. 

@jonaslagoni I don't have that much experience with Modelina and not sure if it's feasible. WDYT? 🤔

**Comment by SinghiHarsh** [comment]
How about we create a CLI function to generate types on the go based on the operationId added or changed in AsyncAPI file. (Just a thought)
I’m looking to implement the idea of creating blueprint files for the message payloads in the AsyncAPI file during the generation of glee project.

**Comment by jonaslagoni** [comment]
That should definitely be possible yea 👍 

In the early stages of Glee we also did this for Java, so you could have Glee functions in Java where the signature of the function was generated by Modelina, like you are proposing for TypeScript. So yea definitely possible 💯

**Comment by KhudaDad414** [comment]
@peter-rr I think you are working on generating glee projects from CLI(If I am not mistaken) I guess step 2 can be done there?

**Comment by AnimeshKumar923** [comment]
@KhudaDad414 issue still valid?
cc: @jonaslagoni

**Comment by KhudaDad414** [comment]
@AnimeshKumar923 This is a valid issue. To address it, we might need to implement this feature in two places:

* **Glee Generator Template:**  For initial type generation when the project is created (Glee Template: [https://github.com/KhudaDad414/glee-generator-template](https://github.com/KhudaDad414/glee-generator-template)).
* **Glee Runtime:** To dynamically regenerate types when the AsyncAPI file changes. 

The challenge is that The Glee Generator Template runs only once. How can we ensure types remain synchronized with AsyncAPI changes afterwards?

**Possible Considerations:**

 Could Glee monitor the AsyncAPI file for changes?
 Can type regeneration be triggered by the user for better control?
