### ISSUE TITLE
Better config management

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#392]
#### Reason/Context
When I want to add something to the config file currently I have to take the following steps:
1) update the `lib/index.d.ts` and add my config types.
2) update the `docs/config-file.md` to reflect the new configs that I have added/changed.
3) If no config is provided in my config file I have to hardcode the default values in adapters themselves.

When working with the codebase, it's a little hard to go back and forth between these files and make sure the are synced and the parsing logic is correct. 

#### Description
IMO we can make some improvements to the codebase and make it easier for the new contributors to understand the codebase by having a config class that is responsible for all three of those above.

1) The class should be documented correctly with `jsdoc` so we can generate the `doc/config-file.md` from it instead of maintaining it separately.

2) all of the parsing logic should be handled by this class itself. I shouldn't have to look around for the port of my server in three different places and finally hardcode the default value in each `Adapter`. 😄 

3) Providing default values for each configuration.

**Comment by Souvikns** [comment]
@KhudaDad414 I am thinking of a design for the config class how about something like this 

```ts
export class GleeConfig {
  private _config: any
  constructor(config){
    this._config = config
  }


  glee() {}
  ws() {
    return new WsConfig(this._config.ws)
  }
  cluster() {}
  mqtt() {}
  http() {}
  kafka() {}
}

class WsConfig {
  private _server
  private _client
  constructor(wsConfig) {
    this._client = wsConfig.client
    this._server = wsConfig.server
  }

  async client(parameters) {
    let auth
    if (typeof this._client.auth === 'function') {
      auth = await this._client.auth(parameters)
    } else {
      auth = this._client.auth
    }
    return {
      ...this._client,
      auth
    }
  }

  server() {
    return {
      ...this._server
    }
  }

}
```

So basically you have a single config class separated from different protocol config classes where we define how our protocol config and also handle the parsing logic. 

> Let me know your thoughts

**Comment by Souvikns** [comment]
@KhudaDad414 lets discuss it in the PR it will be easy.
