### ISSUE TITLE
Refactor ws adapter to reduce its cognitive complexity

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#396]
#### Reason/Context
the [_connect()](https://github.com/asyncapi/glee/blob/master/src/adapters/ws/server.ts#L23) method in `ws` server adapter currently has a cognitive complexity of 35. It's really hard to understand what is going on. plus, SONAR always complains about it in PRs 😆 

#### Description
refactor the _connect() method by grouping it's logic in separate functions for the purpose of readability and maintainability.

**Comment by oviecodes** [comment]
Hello, @KhudaDad414 I would like to take up this issue.
