### ISSUE TITLE
Refactor mqtt `_connect()` method

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#397]
#### Reason/Context
the [_connect()](https://github.com/asyncapi/glee/blob/master/src/adapters/mqtt/index.ts#L33) method in `mqtt` adapter currently has a cognitive complexity of 29. It's really hard to understand what is going on. plus, SONAR always complains about it in PRs.

#### Description
refactor the `_connect()` method by grouping it's logic in separate functions for the purpose of readability and maintainability.

**Comment by oviecodes** [comment]
Hello @KhudaDad414 , I would like to take on this issue. Thanks
