### ISSUE TITLE
add prettier configuration

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#398]
#### Reason/Context
We currently use eslint for the linting purposes but linting can only get us so far.
We can enforce the code styling guidelines in our codebase by having a `prettier` config file to enforce the guidelines that are not covered by the linter. for example: rules regarding semi-colon usage or trailing commas.

#### Description
* Add a `.prettierrc` file to the codebase and try to fine tune it's settings the the current codebase style.
* Reformat the current codebase with prettier.

**Comment by oviecodes** [comment]
Hello @KhudaDad414 , I'd like to take on this issue.

**Comment by Queen-codes** [comment]
Could I be assigned this issue? I would like to work on it.

**Comment by KhudaDad414** [comment]
@Queen-codes it's all yours. 😀

**Comment by Queen-codes** [comment]
Thank you. I'm currently facing some issues while trying to install the necessary dependencies. There is a conflict between the versions of the eslint package required by the different dependencies. Specifically, the eslint-plugin-sonarjs@0.5.0 package requires a peer dependency of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, but this project has installed a higher version of eslint@8.32.0, which is not compatible with the required version. 

I need your guidance on how to resolve this. @KhudaDad414

**Comment by KhudaDad414** [comment]
@Queen-codes I would recommend adding `--legacy-peer-deps` flag to your `npm` command.

**Comment by Queen-codes** [comment]
thank you. appreciate it

**Comment by Queen-codes** [comment]
Hi, @KhudaDad414.  I wanted to let you know that I have submitted a pull request for this issue and  I would really appreciate it if you could take a look at it and provide your feedback. Please let me know if there's anything I can do to help with the review process. Thank you in advance for your time and help.

Best regards,
[your name]

**Comment by Queen-codes** [comment]
Hello @KhudaDad414. I just wanted to let you know that I have submitted a pull request for this issue and I would really appreciate it if you could take a look at it and provide your feedback.  Thank you in advance for your time and help.

**Comment by pragya-20** [comment]
Hi @KhudaDad414, I want to pick it up. Can I start working on it?

**Comment by rukundob451** [comment]
@KhudaDad414 @Queen-codes how far with this issue?

**Comment by KhudaDad414** [comment]
@rukundob451 totally forgot about this one. 🤦 we have a [PR](https://github.com/asyncapi/glee/pull/404) and currently waiting for @Queen-codes to resolve the issue so we can merge it. 
thanks for noticing.

**Comment by rukundob451** [comment]
Well @KhudaDad414, any more issues you would recommend me to work on?

**Comment by KhudaDad414** [comment]
@rukundob451 thanks for your interest.
I think your efforts can be valuable from a user's point of view.
I would suggest creating a simple game or something with Glee and document your experience to see where the improvements are necessary and how it can be improved. :)
please hit me up in [AsyncAPI Slack](https://www.asyncapi.com/slack-invite) if you had any questions.

**Comment by rukundob451** [comment]
@KhudaDad414 thank you for your feedback and suggestion. I appreciate your confidence in my efforts. Creating a simple game using Glee and documenting the experience sounds like an exciting and valuable approach to understanding the tool's strengths and areas for improvement.

I will explore Glee further and work on developing a game using the tool. During the process, I will document my experience, challenges faced, and areas where improvements can be made. This hands-on approach will provide valuable insights into the user experience and help identify areas where the documentation can be enhanced to assist other users. Possibly will need more guidance on how to approach this?

I will make sure to reach out to you on the AsyncAPI Slack channel to discuss more clarification. Your guidance and support will be greatly appreciated.

I'm looking forward to contributing to Glee and its documentation.

**Comment by ConnectBhawna** [comment]
Hii @KhudaDad414 sir, May i make the PR for the same ?
I am done with the changes you specified. Let me know if that works

**Comment by KhudaDad414** [comment]
@Queen-codes do you want @ConnectBhawna to open a new PR?
