### ISSUE TITLE
error when running `npm install` in glee

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#403]
#### Describe the bug
After cloning glee the first step is to run `npm install` to install the dependencies.
With the newer version of `npm` you will get the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-sonarjs@0.5.0
npm ERR! Found: eslint@8.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.6.0" from the root project
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/eslint-plugin@5.49.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^5.9.0" from the root project
npm ERR!     @typescript-eslint/eslint-plugin@"^5.1.0" from eslint-plugin-github@4.6.0
npm ERR!     node_modules/eslint-plugin-github
npm ERR!       eslint-plugin-github@"^4.3.5" from the root project
npm ERR!   15 more (@typescript-eslint/experimental-utils, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from eslint-plugin-sonarjs@0.5.0
npm ERR! node_modules/eslint-plugin-sonarjs
npm ERR!   dev eslint-plugin-sonarjs@"^0.5.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from eslint-plugin-sonarjs@0.5.0
npm ERR!   node_modules/eslint-plugin-sonarjs
npm ERR!     dev eslint-plugin-sonarjs@"^0.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
```
as `npm` suggests adding `--legacy-peer-deps` resolves the issue but there should be a better solution here.
maybe a package needs to be upgraded? 🤔 

#### How to Reproduce
1) clone glee.
2) run `npm i` with npm 8 or higher.

#### Expected behavior
There shouldn't be any errors and dependencies should install.

**Comment by sambhavgupta0705** [comment]
Hey ,I would like to look into this  issue

**Comment by KhudaDad414** [comment]
@sambhavgupta0705 sure. 🙇

**Comment by KhudaDad414** [comment]
@sambhavgupta0705 please open A PR. we can discuss this further over there :)

**Comment by sambhavgupta0705** [comment]
Opening it

**Comment by SinghiHarsh** [comment]
@KhudaDad414 I have upgraded package versions of **eslint-plugin-sonarjs** & **typedoc** 
https://github.com/asyncapi/glee/pull/408

**Comment by SinghiHarsh** [comment]
> Opening it



> Opening it

Hi @sambhavgupta0705 , I tried upgrading the package versions to fix dependency tree error, 
What is your approach ?

**Comment by sambhavgupta0705** [comment]
@SinghiHarsh I had the same approach of upgrading the versions.

**Comment by rukundob451** [comment]
@KhudaDad414 @sambhavgupta0705 what was the conclusion to this is it open?

**Comment by ConnectBhawna** [comment]
Hii @KhudaDad414 @sambhavgupta0705 if no one working on this i would like to work on this issue

**Comment by ayushnau** [comment]
![image](https://github.com/asyncapi/glee/assets/78146753/df58651a-4ab3-4148-8d0f-f5d419f8548d)
cant see the issue.

**Comment by sambhavgupta0705** [comment]
@ayushnau which version of npm are you using?

**Comment by Souvikns** [comment]
same here, I can't reproduce the error as well I am using npm `v9.7.2` and node `v20.4.0`

**Comment by KhudaDad414** [comment]
tested with node `v20`, `v18`, `v16` and it seems like the error doesn't show up anymore. closing the issue.
