### ISSUE TITLE
Better logging for MQTT adapter

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#406]
#### Reason/Context
When I run the glee app with an `mqtt` broker, I receive the following information in my console:
```
{} Running in development mode...
↙↗ Selected server(s): mqtt
────────────────────────────────────────
⚡ Connected to server mqtt.
```

Although these information are useful, I think it is important to log the channels that have been subscribed to or channels that I can publish to. or if there was an error subscribing to a channel.

#### Expected output:
```
{} Running in development mode...
↙↗ Selected server(s): mqtt
────────────────────────────────────────
⚡ Connected to server mqtt.
⚡ Subscribed to `orders` topic.

```
or 
```
{} Running in development mode...
↙↗ Selected server(s): mqtt
────────────────────────────────────────
⚡ Connected to server mqtt.
x Error while trying to subscribe to `orders` topic.
{Error message}

```
#### Implementation
Add error handling logic to the mqtt Adapter here:
https://github.com/asyncapi/glee/blob/bc0d45f805442c013e6a3a294c533155564d5274/src/adapters/mqtt/index.ts#L138

**Comment by himanshu007-creator** [comment]
Hey @oviecodes , if you are not working on this issue i would love to pick it up

**Comment by KhudaDad414** [comment]
@oviecodes If you haven't started working on this issue I guess It makes sense to leave it for @himanshu007-creator. WDYS?

**Comment by oviecodes** [comment]
Alright @KhudaDad414 , that cool. @himanshu007-creator it's all yours.🙇

**Comment by SinghiHarsh** [comment]
Hey @himanshu007-creator , Are you still working on this ?

**Comment by oviecodes** [comment]
Hello @himanshu007-creator , are you working on this issue? i'd like to take it up.

**Comment by kaushik-rishi** [comment]
I'm picking this up, Will try to explore more of glee and get started on this quickly. :slightly_smiling_face:

**Comment by kaushik-rishi** [comment]
@KhudaDad414 I don't understand why are we supposed to add the error handling [here](https://github.com/asyncapi/glee/blob/master/src/adapters/mqtt/index.ts#L117) :slightly_smiling_face:
