### ISSUE TITLE
upgrade parser to version 3(next-major)

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#409]
#### Reason/Context
Following a recent discussion with @Souvikns and @fmvilas it seems like it's a plausible idea to use the latest version (v3.0.0-next-major.5) of @asynapi/parser-js in Glee.

#### Why?
* For solving #391 we have #407 which uses the latest version of modelina and without upgrading the parser in glee, we can't continue with this PR.
* Version 3 of the spec will be released soon and we need the new version of parser to support version 3 of the spec.
* The new intent-api implementation of parser-js in version 2 is way cooler than the current implementation :)

### Scope

- [x] Migrate to Parser v3
- [x] Update MQTT Adapter along with its examples.
- [ ] Update docs
- [ ] Update tests

**Comment by oviecodes** [comment]
@KhudaDad414 I would like to take on this issue.

**Comment by oviecodes** [comment]
hello @KhudaDad414 the latest version (v2.0.0-next-major.15) of @asynapi/parser-js is in pre-release, how do you recommend i go about this task.

**Comment by KhudaDad414** [comment]
@oviecodes by changing the current version to `^2.0.0-next-major.15` in `package.json`, running `npm i`, getting tons of errors, and going after each one. 😀

**Comment by oviecodes** [comment]
@KhudaDad414 I've opened an issue on the `@asyncapi/parser-js` repository

**Comment by ConnectBhawna** [comment]
Hey @KhudaDad414 I would like to take this issue.

**Comment by KhudaDad414** [comment]
@ConnectBhawna that's great. @oviecodes do you plan to continue the work or should it be assigned to @ConnectBhawna?

**Comment by oviecodes** [comment]
@KhudaDad414 please assign it to @ConnectBhawna , thanks.

**Comment by KhudaDad414** [comment]
@ConnectBhawna, let me know if there was anything that I could help with. :)

**Comment by Souvikns** [comment]
/progress 40 
https://github.com/asyncapi/glee/pull/523 is ready for review.

**Comment by KhudaDad414** [comment]
/progress 50
MQTT adapter is compatible with v3(next branch) of parser-js.

**Comment by KhudaDad414** [comment]
/progress 90
PR is ready to merge #523
