### ISSUE TITLE
Proposal for having a tutorial document or separate guides for glee. 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#431]
#### Reason/Context

Currently, it is hard to get started with Glee as a new user, we need some kind of documentation that talks about:

- how to install and setup Glee
- achieve what we are trying to do (details on what tweaks we can make)
- how to deploy glee. 

I think it would really benefit from having tutorial documentation for Glee so as to talk about different features Glee has and also as a user manual for new users to learn from, something like [reactjs tutorial](https://legacy.reactjs.org/tutorial/tutorial.html#taking-turns), or we can have a guides sections where we can have setup by setup guides for achieving certain things, and when we have new features we can create guides to showcase them. 

We need to decide if it is something that would be beneficial, and if we decide on this, how should we go about it, should this be on the website or in the Readme, or on wikis? 

#### Specific Goals 
Just defining what we need to document

- We need to document a getting started guide where we help the user set up a glee project and help him get started with the project. 
- Docs that talk about details on different features of glee, like what are different lifecycle events and how to use them, docs on config, etc. 

> pinging @fmvilas @KhudaDad414

**Comment by rukundob451** [comment]
@Souvikns, is this available to be worked on?

**Comment by rukundob451** [comment]
@Souvikns will be waiting in on your response, thank you.

**Comment by rukundob451** [comment]
> @rukundob451 we are thinking of adding this issue to the mentorship program, nothing is final yet give us some time.

I would surely want to be assigned this issues and work on it during the mentorship program.

**Comment by ConnectBhawna** [comment]
Hii @Souvikns I am interested in working in this issue.
Could you please assign this to me. Or firstly may i need to share my approach for the same

**Comment by maveraw** [comment]
Hi @rukundob451, I am willing to contribute to glee, can you tell me where to submit proposal and do we need to contribute also??

**Comment by AceTheCreator** [comment]
Hey Folks, 

To clarify how to submit a proposal, you should contact the project Mentor/s on Slack and send them your submission in the form of a document or ask them how best they'd prefer you submit your proposals.

**Comment by rukundob451** [comment]
> Hey Folks,
> 
> To clarify how to submit a proposal, you should contact the project Mentor/s on Slack and send them your submission in the form of a document or ask them how best they'd prefer you submit your proposals.

Thank you for the communication @AceTheCreator.
