### ISSUE TITLE
AsyncAPI spec v3 support in Glee

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/glee#457]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Remaining tasks:

- [x] Switch to new parser API (https://github.com/asyncapi/glee/issues/409)
- [x] Once https://github.com/asyncapi/parser-js/issues/780 is solved, update parser dependency (might be automated)
- [x] Update all AsyncAPI dependencies once they are released with AsyncAPI v3 support (mostly automated)
  - [x] https://github.com/asyncapi/markdown-template/issues/341
  - [x] https://github.com/asyncapi/html-template/issues/430
  - [x] https://github.com/asyncapi/generator/issues/979
- [x] #550

**Comment by KhudaDad414** [comment]
/progress 90
after adding support for v3 of parser, Spec 3 version will be supported by default.

**Comment by fmvilas** [comment]
@KhudaDad414 don't forget to support new features like request/reply. That support won't be implicit.

**Comment by KhudaDad414** [comment]
/progress 80

implementation is done. working on docs.

**Comment by KhudaDad414** [comment]
/progress 90

PR #551 is ready for review.
