### ISSUE TITLE
Generating docs failes if project is a git repository. 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#461]
#### Describe the bug
Generating docs is automatic in Glee, but it fails when the project is a git repository. Also, I would want to have no errors right after I create a glee project.

```
x "/Users/postman/Documents/Programs/Learning/greet-bot/docs" is in a git repository with unstaged changes. Please commit your changes before proceeding or add proper directory to .gitignore file. You can also use the --force-write flag to skip this rule (not recommended).
    at Generator.verifyTargetDir (/Users/postman/Documents/Programs/Learning/greet-bot/node_modules/@asyncapi/generator/lib/generator.js:846:71)
    at async Generator.generate (/Users/postman/Documents/Programs/Learning/greet-bot/node_modules/@asyncapi/generator/lib/generator.js:173:29)

```

#### How to Reproduce
To reproduce the bug make sure the project is a glee repository, and just run 

```
npm run start
```

#### Expected behavior
It should create the docs even if my project is a Git repository, and by default I should not see any error logs when I create a new project.

**Comment by rukundob451** [comment]
@Souvikns, I have taken note of the issue when generating the documentation fails when the project is a Git repository with unstaged changes in the `/Users/postman/Documents/Programs/Learning/greet-bot/docs` directory and currently looking into it.

**Comment by Souvikns** [comment]
@rukundob451 do you need any help with this issue, according to the [generator docs](https://www.asyncapi.com/docs/tools/generator/api#Generator+forceWrite)  we can pass `forcreWrite` as true in https://github.com/asyncapi/glee/blob/69e5b907b428d0a12e99bf2a1a9f564241b9c0e4/src/lib/docs.ts#L10


I think this flag was done so that generator does not accidentally rewrite the code, but in our case, we are generating docs which is not a problem if it is re-written.

**Comment by rukundob451** [comment]
Hey @Souvikns, yes needed some help with this!

**Comment by Souvikns** [comment]
Let me know, how I can help you.

**Comment by Souvikns** [comment]
@rukundob451 are you working on this, or should I put this issue up for hacktoberfest?

**Comment by Souvikns** [comment]
I think no one is working on this currently so this Issue is open for hacktoberfest.

**Comment by ankur0904** [comment]
@Souvikns I want to work on this issue.

**Comment by Souvikns** [comment]
sure @ankur0904 go ahead.

**Comment by freakfan15** [comment]
hey @Souvikns, I think no one is working on this, and I understand what to do here. Can I take this up?
