### ISSUE TITLE
Glee command failing in Mac

### ISSUE THREAD

**Issue by Amzani** [asyncapi/glee#471]
#### Describe the bug
```
➜  Projects asyncapi new glee
Error: Unable to create the project. Please check the following message for further info about the error:

Error: ENOENT: no such file or directory, lstat '/usr/local/Cellar/asyncapi/0.50.1/libexec/lib/node_modules/@asyncapi/cli/create-glee-app/templates/default'
```

#### How to Reproduce
I'm using a Mac (13.2)

- brew install asyncapi
- asyncapi new glee

#### Expected behavior

Glee command should work and create an app

**Comment by Souvikns** [comment]
@Amzani the PR is merged, it should work once you update the CLI.

**Comment by Souvikns** [comment]
Closing this as it is fixed now.
