### ISSUE TITLE
Show server url

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#475]
#### Reason/Context
Glee should show the url that it runs it's server or becomes easier to test that server just by clicking on the link instead of looking the url up in the AsyncAPI file.

#### Current output when a server is created:

<img width="897" alt="Screenshot 2023-07-10 at 16 54 28" src="https://github.com/asyncapi/glee/assets/32505158/a2c5358a-c77f-4258-ad57-bb6b19b05a37">

#### Expected output when a server is created:

<img width="897" alt="Screenshot 2023-07-10 at 16 56 21" src="https://github.com/asyncapi/glee/assets/32505158/c7f43b2a-0454-4a45-8d89-3d0c98ec9835">

**Comment by depleur** [comment]
Hey, I can try working on this.

**Comment by KhudaDad414** [comment]
Sure, let me know if you need some help.

**Comment by sudoshreyansh** [comment]
Hi, is this issue available?

**Comment by Souvikns** [comment]
Yeah @sudoshreyansh it is available

**Comment by sudoshreyansh** [comment]
@Souvikns I'll work on it 👍
