### ISSUE TITLE
Create GitHub Action to Render Docs into AsyncAPI Website Pages

### ISSUE THREAD

**Issue by afzal442** [asyncapi/glee#481]
#### Reason/Context
To streamline the documentation process and keep it up-to-date, automating the rendering of documentation from the AsyncAPI specification can be immensely helpful. GitHub Action will be a way to automate repetitive tasks within a GitHub repository for essentially generating documentation from the Glee Docs folder and deploying it to the AsyncAPI website.

#### Description
The action will be triggered on specific events, such as a push to the repository or a pull request to the main branch. The documentation will be rendered and pushed to the appropriate location on the AsyncAPI website to make it accessible to users and developers.

@Souvikns @KhudaDad414 @derberg

**Comment by afzal442** [comment]
tagging you @derberg for any thoughts 😄

**Comment by AnimeshKumar923** [comment]
Hey there @afzal442 ! :wave: 
I like this idea. Are your working on this? I have an approach in mind. It's somewhat similar to how the generator docs are update in asyncapi/website
cc: @derberg thoughts? :eyes:

**Comment by afzal442** [comment]
That's precisely correct approach. I think. You can go head. Thanks. You may find related work here as well https://github.com/asyncapi/cli/pull/476

**Comment by AnimeshKumar923** [comment]
> That's precisely correct approach. I think. You can go head if you want. Thanks.

Okay then. I'll be taking this up and will be reporting back to you as I progress.

> You may find related work here as well https://github.com/asyncapi/cli/pull/476

Thanks for providing reference!

**Comment by AnimeshKumar923** [comment]
I think to get this workflow running, we need to create a `Glee` section in [tools](https://github.com/asyncapi/website/blob/master/pages/docs/tools) under docs section in the main website repository.
cc: @afzal442 @akshatnema @Souvikns @KhudaDad414

**Comment by afzal442** [comment]
Hi @AnimeshKumar923 long time no see. 😄 Do you want to try to give it a shot? LMK

cc @Souvikns

**Comment by Souvikns** [comment]
@AnimeshKumar923 you can pick it up if you want, I think you have to open two PRs one in Glee, and the other in the website repo changing the format, you can start with the Glee side first. Let me understand the full process and get back to you.

**Comment by AnimeshKumar923** [comment]
> Hi @AnimeshKumar923 long time no see. 😄 Do you want to try to give it a shot? LMK

Hey @afzal442 :wave: 
First of all I apologize. My 3rd semester started and got a ton of workload so didn't had the chance to look upon this issue. Meanwhile, I was working a little on this PR https://github.com/asyncapi/community/pull/805 (still awaiting approval on it...), so didn't wanted to pick-up any other issue to focus only on one issue at a time. But I guess the above issue is very close to be resolved the PR, so I think I can pick this up now.
Also, I was just lurking around and seeing what was going on within the community. :eyes:

**Comment by AnimeshKumar923** [comment]
> @AnimeshKumar923 you can pick it up if you want, I think you have to open two PRs one in Glee, and the other in the website repo changing the format, you can start with the Glee side first. Let me understand the full process and get back to you.

Hey @Souvikns :wave: 
I can give this a try but I have little knowledge about the GH Actions and ci/cd with this PR https://github.com/asyncapi/community/pull/805 being the only experience. I may require some assistance with it.
So, shall I proceed with it?

**Comment by afzal442** [comment]
Hi @AnimeshKumar923, all you can do is trying out creating github action yml files for updating docs similar to https://github.com/asyncapi/cli/blob/master/.github/workflows/update-docs-in-website.yml and https://github.com/asyncapi/cli/blob/master/.github/workflows/update-docs-on-docs-commits.yml

Let us know if you need any help.

**Comment by afzal442** [comment]
Sorry @AnimeshKumar923 did you get time around it? Let us know.

**Comment by sambhavgupta0705** [comment]
@afzal442 to resolve this you need to make a pr in glee same as this [https://github.com/asyncapi/cli/blob/master/.github/workflows/update-docs-in-website.yml](https://github.com/asyncapi/cli/blob/master/.github/workflows/update-docs-in-website.yml) and also a folder in wesbite 
just like this https://github.com/asyncapi/website/pull/2226

**Comment by AnimeshKumar923** [comment]
> Sorry @AnimeshKumar923 did you get time around it? Let us know.

No worries man. Will start it today for sure...👍🏻

**Comment by AnimeshKumar923** [comment]
I had created an issue in July inside the website repo with the knowledge I had at that time. In the discussion, Lukasz mentioned the following things:

> to start pushing Glee or any other docs to website, there is nothing that must be done in the website

> you need automation in glee, like:

    cli example: https://github.com/asyncapi/cli/blob/master/.github/workflows/update-docs-in-website.yml
    generator example: https://github.com/asyncapi/generator/blob/master/.github/workflows/update-docs-in-website.yml

> the only thing that is not there in examples, is something that was added later, a config file for Edit button. So the automation you add, should also edit https://github.com/asyncapi/website/blob/master/config/edit-page-config.json and add your repo there

Does this implies that I only have to create the two workflows [mentioned here](https://github.com/asyncapi/glee/issues/481#issuecomment-1769052403) and the `folder creation idea inside the website repo` will be taken care of?

cc: @afzal442 @sambhavgupta0705

**Comment by AnimeshKumar923** [comment]
I have raised an initial PR according to your suggestions.
Please give your feedback @afzal442 @sambhavgupta0705 

cc: @Souvikns

**Comment by afzal442** [comment]
Nice job @AnimeshKumar923 ! I can't review your PR since it's against github action workflow. only members can. but appreciate it.
