### ISSUE TITLE
Specifying functionsDir or lifecyclesDir in config file results in an error

### ISSUE THREAD

**Issue by oviecodes** [asyncapi/glee#509]
#### Describe the bug
An Error occurs when you try to specify the `functionsDir` or `lifecycleDir` in the `glee.config.ts` file as a result of glee not reading the files from the `.glee` directory whenever these values are specified.

#### How to Reproduce
In the client directory of any example in the Glee repo, create a `config.glee.ts` file, then specify the `functionsDir` as follows:

```ts
export default async function () {
  return {
    glee: { // Glee core configurations
      lifecycleDir: './lifecycle',
      functionsDir: './functions', 
    }
  }
}
```

In the `functions` folder, create a function file with `.ts` extension.

You should get the following error:

<img width="1440" alt="Screenshot 2023-08-21 at 2 31 34 PM" src="https://github.com/asyncapi/glee/assets/61796959/00e87b1b-56a3-404c-b6bb-99c2016cf200">

#### Expected behavior
Glee should be able to resolve `.ts` files when `lifecycleDir` and `functionsDir` is specified in `glee.config.ts`

@Souvikns @KhudaDad414

**Comment by afzal442** [comment]
Hey @oviecodes are you able to run `npm run dev` without error? if not, how did you resolve that? 

Are you facing the abv error after specifying the dirs? Since I am also testing out the examples for the docs, LMK.

**Comment by oviecodes** [comment]
Hey @afzal442 please add an image of  the error you're getting here... That would help me understand better

**Comment by afzal442** [comment]
Sorry @oviecodes I got it fixed now. Thanks for your quick reply. 😄

**Comment by oviecodes** [comment]
#517 should fix this issue @Souvikns @KhudaDad414
