### ISSUE TITLE
Add required support for existing adapters

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#514]
### Scope

- [x] https://github.com/asyncapi/glee/issues/377
- [ ] https://github.com/asyncapi/glee/issues/411

**Comment by oviecodes** [comment]
hello @fmvilas authentication layer for glee #377 was done as part of GSOC, Here's the pull request #472  and the docs PR #507 , I'll take a look at #411

**Comment by KhudaDad414** [comment]
/progress 10
started looking into kafka bindings...
