### ISSUE TITLE
Release Glee v1 and add support for spec 3.0

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#518]
_(This issue has been created with the purpose of grouping the tasks below. Please comment on these issues instead.)_

### Scope

- [x] #409 
- [x] #377
- [x] #457
- [x] #558
- [x] #557
- [x] #556
- [x] #553

### Optional

* #563
* #555

**Comment by Amzani** [comment]
@fmvilas I suggest to  
- Remove #514 from the scope. As discussed with @KhudaDad414 and @Souvikns we can release Glee v1 with Spec 3.0 and Auth (#377). 
- Convert #514 to a Bet that we deliver in the next cycle

**Comment by fmvilas** [comment]
Sure, that should work 👍

**Comment by KhudaDad414** [comment]
@fmvilas 
I suggest the following issues for the next cycle:
https://github.com/asyncapi/glee/issues/558
https://github.com/asyncapi/glee/issues/557
https://github.com/asyncapi/glee/issues/556
https://github.com/asyncapi/glee/issues/555
https://github.com/asyncapi/glee/issues/553
https://github.com/asyncapi/glee/issues/563
https://github.com/asyncapi/glee/issues/411

**Comment by fmvilas** [comment]
I'd mark the following as optional for the next cycle because they're not trivial:
* #555 
* #563 

And clarify who's gonna own #411 and #556 because @oviecodes expressed interest too.

**Comment by oviecodes** [comment]
I'm on #411 @fmvilas , @Souvikns  is taking #556 .

**Comment by fmvilas** [comment]
Thanks, @oviecodes 🙏
