### ISSUE TITLE
[Bug] Unauthorized error on auth user data while running through crypto-websockets example

### ISSUE THREAD

**Issue by afzal442** [asyncapi/glee#524]
#### Describe the bug
Unauthorised access issues while accepting connection over websocket

#### How to Reproduce
Steps to reproduce the issue
Run server and client on crypto-websockets

Error:
```
⚡ Running authentication on server websocket.
token bearer arb-tokenValue
userpass { username: 'alec', password: 'oviecodes' }
x 401 Unauthorized
    at WebSocketsAdapter.done (file:///workspaces/glee/dist/adapters/ws/server.js:151:29)
```
On client side:
```
GETING ERROR
x Unexpected server response: 401
    at ClientRequest.<anonymous> (/workspaces/glee/node_modules/ws/lib/websocket.js:783:7)
```

**Comment by afzal442** [comment]
Hey @oviecodes LMK if I have missed sth.

**Comment by oviecodes** [comment]
Are you good on this @afzal442 ,

You're meant to write your authentication logic before calling `done(true)` or done(false)`, depending on the results of your logic

**Comment by afzal442** [comment]
> You're meant to write your authentication logic

I am afraid, wdym?
