### ISSUE TITLE
 allcontributors PRs gets stuck

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#562]
#### Describe the bug
Any PR that is being added by `allcontributors` gets stuck and can't be merged.

example:

https://github.com/asyncapi/glee/pull/560
https://github.com/asyncapi/glee/pull/554

**Comment by Souvikns** [comment]
Only happening in this repo? It works fine in `CLI`, should we update `allcontributors` manually for now.

**Comment by KhudaDad414** [comment]
@Souvikns I will take a look into this issue. I think the problem is with testing, test results never get reported. 🤔

**Comment by derberg** [comment]
it is because `skip_ci` info in description of PR

fix with https://github.com/asyncapi/cli/blob/master/.all-contributorsrc#L338
