### ISSUE TITLE
Implement Binding Version Check to Ensure Compatibility and Stability

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#570]
### Reason/Context
AsyncAPI's strength lies in its extensibility through protocol bindings. These bindings are independently versioned, and Glee's support is tied to specific binding versions. Changes or updates in these bindings can potentially disrupt Glee's functionality or lead to unexpected behavior.

### Description

To enhance robustness and user awareness, Glee should implement a version check for protocol bindings. Before parsing, Glee needs to verify if the binding version is one that it currently supports. If the version is unsupported, Glee should issue a clear warning. This warning should inform the user that while Glee will attempt to work with the provided bindings, this might lead to system instability. Additionally, it should prompt the user to report this incompatibility by opening a new issue in the Glee repository, requesting support for the newer binding version.

### Solution
Integrate this feature directly into Glee's core functionality. Adapter modules should declare the binding versions they support. Glee, in turn, should handle the compatibility checks based on these declarations. This approach centralizes version management within Glee, simplifying the process for both developers and users.

**Comment by ayush3160** [comment]
@KhudaDad414 , Can I work on this ?

**Comment by KhudaDad414** [comment]
yes, feel free to pick it up. @ayush3160
