### ISSUE TITLE
Simplify `done()` Function to Only Accept Boolean for Authentication Status

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#596]
### Context
The current implementation of the `done()` function allows specifying custom error codes and messages, which might lead to inconsistencies and over complication, especially in standard HTTP authentication cases. This proposal is to simplify the `serverAuth` function to accept only a Boolean value indicating authentication success (`true`) or failure (`false`).

### Current Behavior
The `done()` function currently accepts the following parameters:
- A Boolean value indicating the authentication status.
- An optional HTTP status code.
- An optional error message.

Example:
```javascript
serverAuth({ authProps, done }) {
  // Various invocation possibilities
  // done(true)
  // done(false, 401, "Unauthorized")
  // done(false)
}
```

### Proposed Change
Simplify the `done()` function to accept only a Boolean value:
- `true` for successful authentication.
- `false` for failed authentication.

In cases of authentication failure, the function should automatically set the HTTP status code to `401 Unauthorized`.

**Comment by ankur0904** [comment]
Hey @KhudaDad414  
I am interested in working on this issue but would need discussion. Can we discuss about this issue on Slack?

**Comment by KhudaDad414** [comment]
@ankur0904  Sure. just text me on AsyncAPI Slack.
