### ISSUE TITLE
Move `x-remoteServers` Configuration to `glee.config.(js|ts)`

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#601]
### Context
Currently, Glee specifies which servers are remote by using the `x-remoteServers` attribute in the AsyncAPI file. It is proposed to move this configuration to the `glee.config.(js|ts)` file, as this is a configuration specific to Glee, rather than to the API itself.

#### Current Implementation
In the current setup, the AsyncAPI file contains the `x-remoteServers` attribute:

```yaml
x-remoteServers:
  - httpbin.org
```

#### Proposed Implementation
The new configuration would be part of the `glee.config.(js|ts)` file, making it more intuitive and aligned with other Glee configurations:

```javascript
export default async function () {
  return {
    glee: { // Glee core configurations
      remoteServers: ["httpbin.org"],
      // ... other configurations
    },
    // ... other configurations...
  }
}
```

**Comment by afzal442** [comment]
Hi, is this related to code change to support the outcome and let logic do the work or just moving the config?

**Comment by KhudaDad414** [comment]
@afzal442 the logic works as explained. it parses it from the AsyncAPI file. 

https://github.com/asyncapi/glee/blob/2b747d592588ee22774f79cbdd5c7f4173e01dbb/src/registerAdapters.ts#L44

we need to first change the code logic to get it from the config file and update the documentation as well.

**Comment by afzal442** [comment]
I think it is going to be tricky for me as it has to do sth extracting the value from glee.confile file.

**Comment by ayush3160** [comment]
@KhudaDad414 , I would like to work on this issue.
