### ISSUE TITLE
Support for Multiple .env Files

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#638]
**Reason/Context:** 
Currently, Glee only supports parsing environment variables from the `.env` file. However, the capability to parse additional environment configurations from files like `.env.local` is missing. This feature is essential for handling different environments more effectively, such as development and production.

**Proposed Solution:** 
To enhance Glee's environment parsing capabilities, I propose we integrate the `@next/env` package. This package efficiently manages multiple `.env` files, automatically loading appropriate environment settings based on the application's context. This integration will streamline Glee's configuration process and align it with common development practices.

**Comment by AkhilJ321** [comment]
@KhudaDad414. So here we are looking for a functionality , where we have multiple envs like .env.production .env.development and then according to NODE_ENV specific env is used.SO we can acheive this thing by ```require('dotenv').config({ 
    path: `.env.${process.env.NODE_ENV}` 
});```.

**Comment by AkhilJ321** [comment]
@KhudaDad414 ,I made the changes in code, but i am confused about how to test this thing out in my local setup.

**Comment by KhudaDad414** [comment]
@AkhilJ321, I suggest you follow the following steps:
1) Install `@next/env`.
2) Use the `loadEnvConfig` function to load the configuration in the `index.ts` file of Glee. It should be something like `loadEnvConfig(GLEE_PROJECT_DIR, isDev)`. You can check if it is a development environment by verifying whether `process.env.NODE_ENV` is set to `development` or `production`.

3) Document how Glee can now support multiple .env files. You can draw inspiration from [Next.js environment variables documentation](https://nextjs.org/docs/basic-features/environment-variables) since Glee will use Next.js's package, and the functionality will be the same.

4) For testing, run one of the examples and then create files like `.env`, `.env.local`, `.env.production`, `.env.development`, adding environment variables to them. Afterwards, log these variables in the example's function to see if it picks up the variables as expected.
