### ISSUE TITLE
Improve Stability in Glee by Handling Message and Connection Failures

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#640]
**Reason/Context:** 
Glee currently experiences crashes when message delivery fails or a server connection cannot be established. Ideally, Glee should continue to operate normally under these circumstances, without interruption.

**Proposed Solution:** 
To enhance Glee's resilience, I propose implementing try/catch blocks inside all of the `send()` and `connect()` methods across all adapters.

Implementing this broadly will prevent crashes and improve overall stability.

**Comment by HarshDeep61034** [comment]
Assign this issue to me, I would love to work on this.
