### ISSUE TITLE
Apply `default` property to event fields

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#659]
#### Reason/Context
If we apply the `default` property value to event fields, users will need less boilerplate in their functions (i.e., checking for the existence of a value).

#### Description
For instance, I have the following definition (notice the `default` value on the `repeat` field):
![Captura de pantalla 2023-12-18 a las 11 39 41](https://github.com/asyncapi/glee/assets/242119/018371c7-b2f2-46e0-8ac2-a7f7fbf1a009)

Right now, the following code will fail if `event.payload.repeat` is undefined:
![Captura de pantalla 2023-12-18 a las 11 40 49](https://github.com/asyncapi/glee/assets/242119/3eb05ccf-76e7-41c8-b5f7-18cde299ad91)

I think it shouldn't fail since, in our schema definition, we're saying the default value should be 1.

EDIT: After fixing the code above so it doesn't fail, I noticed another thing:

<img width="598" alt="Captura de pantalla 2023-12-18 a las 11 56 04" src="https://github.com/asyncapi/glee/assets/242119/4a93705a-be51-42c5-a637-0c905373692b">

If we don't provide support for this, the default value of 1 is defined in two places: in the schema definition (`default: 1`) and implicitly in the code (`... || 1`). This makes things harder to maintain and keep right. For instance, if the default value changes in the code but not in the schema or vice versa, there will be an inconsistency.

**Comment by Min2who** [comment]
@fmvilas what do yu think we should try to do ? the code should not fail if the event.payload.repeat is undefined.we are trying to solve this only right?

**Comment by KhudaDad414** [comment]
@Min2who I think the problem here is a little more complicated.
IMO we need to follow the following approach whenever we are dealing with schemas and the "data" that we validate against that schema.

1) load the defaults from the schema. 
2) Deep merge the loaded default to the "data" giving priority to the "data" itself.
 🤔

**Comment by fmvilas** [comment]
I think this will increase DX a lot and still makes sense.
