### ISSUE TITLE
Improved Error Messaging for Missing Auth Function

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#688]
#### Context
While working with the Glee framework, I encountered a WebSocket client error when there was no authentication function present. The current error message does not specify which function is missing or the exact location in the code where the function is expected to be.

#### Error Encountered
```
x WebSocket client error on channel 'SlackEventStream'
at WebSocket.<anonymous> (file:///Users/khudadad/Projects/asyncapi/glee.worktrees/fix-websocket-bug/dist/adapters/ws/client.js:76:40)
...
```

#### Expected Behavior
When the framework encounters a missing authentication function, it would be beneficial for the error message to clearly state which specific function is missing and in which file. For instance, an error message like:
```
Error: Authentication function not found in `auth/Slack_Server`. Expected function `clientAuth`.
```

**Comment by srini047** [comment]
@KhudaDad414 If this issue is open to contributing I would like to take this up.

**Comment by Min2who** [comment]
@KhudaDad414 may i give it a go?

**Comment by KhudaDad414** [comment]
I guess we should go on the First Come First Serve basis. Sorry @Min2who.

@srini047 Please open a PR fixing the issue. If you need help, please reach out.
