### ISSUE TITLE
Parameters in channel address not used

### ISSUE THREAD

**Issue by dankar** [asyncapi/glee#722]
#### Describe the bug
I have an MQTT protocol specification (asyncapi 3.0.0) which uses parameters in the addresses. These seem to be ignored by glee when it subscribes to the topics.

#### How to Reproduce
Create receive channel as follows:
```
channels:
  createUser:
    address: createUser/{userId}
    messages:
      createUser:
        payload:
          type: object
          properties:
            name:
              type: string
    parameters:
      userId:
        $ref: '#/components/parameters/
components:
  parameters:
    userId:
      examples: ['test']
```

What happens is that glee will subscribe to the topic 'createUser/{userId}' (literally).

#### Expected behavior
I guess it's open for debate what the expected behaviour should be, but I expect something along the lines of:
1. glee subscribes to 'createUser/+' where + is a wildcard accepting any value
2. glee provides the value for userId as parameter to the handler function.

Or optionally: some sort of call to enable subscriptions to a channel with a specific parameter value supplied.

Additionally, there seems to be no mechanism for sending a message to a channel which has parameters in the address. Maybe that should be another bug, but it's a bit moot at the point since it seems like the specified address is ignored when sending message on a channel (https://github.com/asyncapi/glee/issues/721)

**Comment by KhudaDad414** [comment]
@dankar. that makes sense. can you open a PR adding this functionality?

**Comment by dankar** [comment]
@KhudaDad414  I don't know the code base of this project enough to do this myself at this point. But if I get around to it some day, I will of course open a PR.
