### ISSUE TITLE
[FEATURE] Run Glee in a container

### ISSUE THREAD

**Issue by eelcofolkertsma** [asyncapi/glee#735]
### Why do we need this improvement?

Setting/maintaining a fully functional node environment on local machine can be overwhelming and hard to debug. A container is much easier to deploy/manage

### How will this change help?

The prerequisite effort to install Docker or equivalent is shared over many projects. 
On download of the compose.yaml a simple "docker compose up" launches the Glee server with default settings. From there you can modify the Glee files and stop/restart the Glee server to explore all features of Glee

No need to worry about install of node, .gyp, python etc

### How could it be implemented/designed?

A (docker) compose.yaml that pulls asyncapi/cli image, runs new glee, npm install, npm run dev commands and attaches to local filesystem. 

A refinement of below yaml

- get away from USER root
- .gyp and python to be included in cli image
- improve naming of directory in local file system
- smart permissions on directory in local file system
- documentation on usage

```
version: '3'

services:
  glee:
    build:
      context: .
      dockerfile_inline: |
        FROM asyncapi/cli
        USER root
        RUN apk add --no-cache --virtual .gyp python3 make g++ && \
            rm -rf /var/lib/apt/lists/* && \
            asyncapi new glee && \
            cd project && \
            npm install
        ENTRYPOINT 
    volumes:
      - ${PWD}/output:/app 
    networks:
      - default
    user: root
    entrypoint: []
    working_dir: /app/project
    command: npm run dev
    
networks:
  default: {}
```

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by KhudaDad414** [comment]
Hey @eelcofolkertsma,

I'm still getting the hang of Docker, but here's how I see it: we code locally, and the container handles the environment and runs everything, right?

If that's the plan, I'm all good with it! Would love a PR when you get a chance.

**Comment by AayushSaini101** [comment]
@KhudaDad414 can we reopen this issue ?
