### ISSUE TITLE
[FEATURE] invoke send action for operation in v3

### ISSUE THREAD

**Issue by eelcofolkertsma** [asyncapi/glee#758]
### Why do we need this improvement?

Today “send [messages]” expects channel, server, and payload as input. Per v3.0.0 this can be upgraded to expect an operation and payload as input.

### How will this change help?

With this change both “receive” and “send” operations have direct link to Glee constructs

### How could it be implemented/designed?

Amend Glee code and documentation

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by KhudaDad414** [comment]
Please go ahead with the PR when you've got the time. 🙇
